### ISSUE TITLE
S1 - User Profile Creation

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#1]
- As a public user, I want to create a unique profile with a profile picture, user name, contact email, and phone number, so that I can personalize my account and receive relevant notifications.

> - MoSCoW : M
> - Business Value : XL
> - Risk : S

- Acceptance Criteria:
> - Profile creation form includes fields for profile picture, user name, email, and phone number.
> - User receives confirmation upon successful profile creation.

**Tasks**
- [x] T1 - Registration - Create Profile (3 point)
   -  A profile has a profile picture, user name, contact email, and phone number.
- [ ] T2 - Confirmation (1 point)
   - The user receives confirmation upon successful profile creation. (optional)

**Testing**
 - [x] Test - Verify Login (1 point)
   - Verify username and password
 - [x] Test - Verify Registration (1 point)
   - Verify that profile has profile picture, user name, email, and phone number.

**Total story points : 6**
