### ISSUE TITLE
S10 - Forum

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#10]
- As a user, I want access to a forum where I can post and reply to discussions related to condo management, so that we can have a common place to share opinions, concerns, recommendations, etc with everyone living in the building, as well as the company owning the building.
> - MoSCoW : S
> - Business Value : M
> - Risk : L
- Acceptance Criteria:
> - Forum interface allows users to create threads and reply to existing discussions.

**Tasks**
- [ ] T1 - Create a "Forum" interface where only users of that building have access as well as management (4 points)
- [ ] T2 - A user can post a question on the forum (3 points)
- [ ] T3 - A user can comment on any posts (2 points)
- [ ] T4 - A user can delete or modify a post or a comment (1 point)
- [ ] T5 - A role has to be attributed to each different types of user (2 points)

**Test**
- [ ] Test - Verify that the forum is only accessible by the people of that building (1 point)
- [ ] Test - Verify that the forum updates with each new comment or post (1 point)
- [ ] Test - Verify that a deleted post or comment is not visible in the forum (1 point)
- [ ] Test - Verify that the database is updated with each new entry or deletion of the forum (2 points)

**Total story points : 17**
