### ISSUE TITLE
S11 - Events and Offers

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#11]
- As a user, I want the ability to organize events and view discounts/offers provided by the condo management company, so that i can be more involve in the community of the building.
> - MoSCoW : S
> - Business Value : M
> - Risk : S
- Acceptance Criteria:
> - Events page allows users to create and manage events.
> - Offers page displays current discounts and offers.

**Tasks**
- [ ] T1 - Create an event page where management can manage and create new discounts/offers (2 points)
- [ ] T2 - The management can create offers and discounts that will be shown on the offer page (2 points)
   - Can add a picture to make an add, or just plain text

**Test**
- [ ] Test - Verify that a new offer is being displayed on the offer page (1 point)

**Total story points : 5**
