### ISSUE TITLE
S13 - Multilingual Support

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#13]
- As a user, I want the app to be available in English and at least one other language, so that the app is more accessible to non English speakers (French).
> - MoSCoW : M
> - Business Value : L
> - Risk : S
- Acceptance Criteria:
> - App interface and content are translated and accessible in multiple languages.

**Tasks**
- [ ] T1 - Add a button to switch from English to French (1 point)
- [ ] T2 - Set up the react multi-language or other similar packages (3 points)

**Test**
- [ ] Test - Verify that all pages are translated (2 points)

**Total story points : 6**
