### ISSUE TITLE
S14 - SSO

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#14]
- As a user, I want the option to log in using my Gmail or other accounts for easier access, so that it'll be easier for me to access the app and my profile.
- Acceptance Criteria:
> - Single sign-on options are available on the login page.
> - Users can authenticate using their preferred accounts.

**Tasks**
- [ ] T1 - Link a google account (10 points)

**Test**
- [ ] Test - Test if the Google account is linked to the user (3 points)
- [ ] Test - Check if all important services are available (2 points)

**Total story points : 15**
