### ISSUE TITLE
S2 - Registration Key Usage

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#2]
- As a public user, I want to enter a registration key obtained from the condo management company to become a condo owner or rental user in the system, so that I can be able to manage my properties or rent, I will be able to communicate with my landlord or the company.

> - MoSCoW : M
> - Business Value : XL
> - Risk : S

- Acceptance Criteria:

> - Registration key entry field is available during account creation or modification.
> - System verifies registration key validity before allowing account creation or modification.

**Tasks**
- [x] T1 - Add input fields for condo registration key (1 point)
   - A user has to be able to input a key and it gives access to the "Manage Property" interface.
- [x] T2 - Create a page for "Manage Property" (1 point)
   - A blank page for now
- [x] T3 - Link the key to the backend (2 points)
   - The key has to be linked to the user that used it. Only the authorized users can have access to their assets.
- [x] T4 - The authorized user must be able to modify or add keys (1 point)

**Test**
- [x] Test - Verify that user is renting or owning the condo to access the  "Manage Property" interface (2 points)
   - Verify that the user is indeed a condo owner or rental
   - Verify that the condo information match the condos linked to the user
- [x] Test - Verify the validity of the registration key (1 point)
- [x] Test - Verify that the authorized user have access to the "Manage Assets" interface (1 point)
- [x] Test - Verify that the field is accessible when editing or adding a key (1 point)

**Total Story Points : 10**
