### ISSUE TITLE
S3 - Dashboard View

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#3]
- As a condo owner, I want to view general information about my properties, including personal profile, condo information, financial status, and status of submitted requests, so that I can at a glance be able to view all the important information about my properties and financial status.

> - MoSCoW : M
> - Business Value : XL
> - Risk : S

- Acceptance Criteria:

> - Dashboard displays personal profile, property details, financial status, and request status in a clear layout.

**Tasks**
- [x] #27
   - Create a page that has the following options: "Manage Property", "My Profile", "Financial Status", and "Submitted Requests"
   -  Manage Property: from the blank page created in S2, The user has to be able to view all the information of the property. (Redirect to NotFound Page for now)
   - My profile must be directed to the user profile, [add all necessary fields]
   - Financial status will be shown on the home page. **Edit: Some financial informations are shown in the property cards in the dashboard. For a more in depth view, it user should be redirected to a different page.**
   - Submitted Requests shows the status for the request of the user. **Edit: Requests will be shown on another page. (Redirect to NotFound Page for now)**
 - [x] T2 - Link to the backend (4 story points)
    - All info from this page has to come from the database
    - All modification must be updated in the database

**Test**
- [x] Test - Verify that the user is authorized to access this dashboard (1 point)
- [x] Test - Verify that the user accesses the right dashboard (1 point)
- [x] Test - Verify that all pages are accessible and that the user does not lose connection (1 point)

**Total story points : 13**
