### ISSUE TITLE
S4 - Property Profile Creation

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#4]
- As a condo management company, I want to create profiles for properties under my management, including property name, unit count, parking count, locker count, and address, so that I can add them to the dashboard.
> - MoSCoW : M
> - Business Value : XL
> - Risk : S
- Acceptance Criteria:
> - Property profile creation form includes fields for all required information.
> - Newly created property profiles are accessible and editable by authorized personnel.

**Tasks**
- [x] T1 - Create a "Create new profile" for a new asset (2 points)
   - Create profiles for properties, including property name, unit count, parking count, locker count, and address.
- [x] T2 - Link the new profile to the backend (1 point)
- [x] T3 - Make the listing accessible and editable by the authorized users (2 points)

**Test**
- [x] Test - Verify that the listing has been added to the database (1 point)
- [x] Test - Verify that all the fields have been filled correctly (1 point)
- [x] Test - Verify that only the authorized users have access (2 points)
- [x] Test - Verify that modifications are updated to the database (1 point)

**Total story points : 10**
