### ISSUE TITLE
S5 - Condo Files Upload

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#5]
- As a condo management company, I want to upload condo files (e.g., declarations, budgets) for each property, accessible to all condo owners of that building, so that the owners may have access to important information about their properties. It also helps with communication with the owners.
> - MoSCoW : S
> - Business Value : M
> - Risk : M
- Acceptance Criteria:
> - File upload functionality is available within each property profile.
> - Uploaded files are accessible to condo owners upon login.

**Tasks**
- [x] T1 - Create an option to upload a condo file (2 points)
- [x] T2 - Link to the database (1 point)
- [x] T3 - Give access to the condo owners the new file (1 point)

**Test**
- [x] Test - Verify that only authorized users can add or modify the files (1 point)
- [x] Test - Verify that the file has been updated to the database (1 point)
- [x] Test - Verify that the authorized users can access the new files (1 point)
 
**Total story points : 7**
