### ISSUE TITLE
S6 - Condo Fee Management

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#6]
- As a condo management company, I want to set condo fees per square foot and per parking spot, and calculate fees for each unit owner, so that I can manage the properties in my buildings.
> - MoSCoW : M
> - Business Value : XL
> - Risk : M
- Acceptance Criteria:
> - System allows input of condo fee rates.
> - Condo fee for each unit is calculated accurately based on set rates and unit size.

**Tasks**
- [ ] T1 - From the asset page of the authorized user, make the fee editable (1 point)
- [ ] T2 - Link the change to the database (1 point)
   - Calculate the new rate for the condos affected by the change

**Test**
- [ ] Test - Verify that the new fee is a possible value (1 point)
- [ ] Test - Verify that the fee was updated to the database (1 point)
- [ ] Test - Verify that the new fee for a condo is correct (1 point)

**Total story point : 5**
