### ISSUE TITLE
S7 - Financial Reporting

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#7]
- As a condo management company, I want the system to generate an annual financial report, summarizing collected condo fees for the year, so that I can have access to a user friendly and useful report which I can have access.
> - MoSCoW : M
> - Business Value : XL
> - Risk : M
- Acceptance Criteria:
> - Annual financial report includes total collected fees for each property.

**Tasks**
- [ ] T1 - Generate data sheet using the data from the database for the user (2 points)
- [ ] T2 - Create a UI-friendly report with all the information and summary (3 points) 
- [ ] T3 - Send the report to the user automatically once a year (1 point)

**Test**
- [ ] Test - Verify that the data from the database is the same as the report created (1 point)
- [ ] Test - Verify that the user receives the report (1 point)
- [ ] Test - Verify that only authorized user have access to their reports (1 point)
- [ ] Test - Verify that the calculations are accurate (2 points)

**Total story points : 11**
