### ISSUE TITLE
S8 - Facility Reservation

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#8]
- As a condo owner or rental user, I want to reserve common facilities in a calendar-like interface, so that I can have access to with reservations to my building's facilities.
> - MoSCoW : S
> - Business Value : M
> - Risk : M
- Acceptance Criteria:
> - Reservation system displays available time slots for each facility.
> - Users receive confirmation upon successful reservation.

**Tasks**
- [x] T1 - Create a calendar-like page (3 points)
   - _[Create__ our own or use google API]_
 - [x] T2 - Management must be able to add available slots for each facility for each condo that will be shown on the calendar (4 point)
    - The user must specify if a facility is on reservation only or if it is open for everyone
    - The user must specify the opening hours, and also closures if necessary
 - [x] T3 - Rental and owner users must be able to choose a time slot for a facility if available.  (3 points)
    - The user must be able to choose from the available slots
    - The system must book the slot and remove the availability on the calendar
 - [x] T4 - Link the calendar to the backend (2 points)
    - The database must keep track of the reservations
 - [x] T5 - Send a notification to both parties when a slot is booked (2 point)
    - Give the option to not receive a notification
 - [ ] OPTIONAL - Link the calendar to google account, send an email/notification to the users when the reservation is near (3 points)

**Test**
- [x] Test - Verify that the calendar accurate (2 point)
  - _If Google API is used, make sure that the connection is up and secured_
- [x] Test - Verify that the management can add and modify the date and time and the change is reflected in the database (2 points)
- [x] Test - Verify that when a slot is booked, both users receive a notification (3 point)
   - Verify that if the option to receive a notification is on, the user receives the notification
   - Verify the contrary of the point above
- [x] Test - Verify that the database is updated when a booking has been made (2 points)
- [x] Test - Verify that when a slot has been booked, no other user can book that same slot (1 point)
- [x] Test - Verify that if a facility does not require a booking, no one can reserve a slot (1 point)
- [ ] OPTIONAL Test - Verify that the google account is linked and an email has been sent (2 points)

**Total story points : 23, OPTIONAL : 5**
