### ISSUE TITLE
S9 - Request Submission and Handling

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#9]
- As a condo owner, I want to submit various requests (e.g., moving in/out, access requests) and track their status, so that I can make decision directly on the app with a more interaction friendly way with the company owning the building.
> - MoSCoW : S
> - Business Value : L
> - Risk : M
- Acceptance Criteria:
> - Request submission form includes options for various request types.
> - Assigned employees receive notifications of new requests.

**Tasks**
- [x] T1 - A user must be able to create a ticket for a request (2 points)
- [x] T2 - The request must be added to the database as "Submitted" (1 point)
- [x] T3 - The request must be shown in the user dashboard with the current status (1 point)
- [x] T4 - The management must receive a notification with the request attached (8 points)
   - The management will start the process of the request as "Processing" for the status
   - Depending on the action, the management can respond to the request
   - The management can then close the request as "Closed" for the status

**Test**
- [x] Test - Verify that the fields are filled correctly (1 point)
- [x] Test - Verify that the ticket is received in the database, and the management receives the notification with the request (2 points)
- [x] Test - Verify all actions are possible for the management depending on the request (4 points)
- [x] Test - Verify that the right employee receives and handles the request (1 point)
 
**Total story points : 18**

**Comment by arcvelit** [comment]
Reopening, was closed prematurely
